name: "KITTI_odometry"
labels: # ground labels
  -1: "out of range"
  0: "ground"
  1: "not ground"  
color_map: # bgr
  -1: [0, 0, 0]
  0: [0, 247, 0]
  1: [0, 0, 248]  
split: #sequence number
  train: 
    #- 0
    #- 1
    #- 2
    #- 3
    #- 4
    #- 5
    #- 6
    #- 7
    #- 8
    #- 9
    #- 10
  valid:
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
  test:
    #- 8
    #- 18
    

    